### ISSUE TITLE
support min and max uncore freq

### ISSUE THREAD

**Issue by AndreasGocht** [readex-eu/libfreqgen#4]
To allow the resetting of the default uncore frequencies a get and set for the min and max uncore frequency would be needed.

**Comment by umbreensabirmain** [comment]
@rschoene Is it already addressed?

**Comment by rschoene** [comment]
If it would be addressed, it would be closed

**Comment by rschoene** [comment]
Added with cf511e575d6e194680ed9de9c1c47bd952aa44b4
